### PR TITLE
making the display looks the same and adding units

### PR DESCRIPTION
**Pull request by Eb-Zeero**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/nir-simulator/75)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/nir-simulator/75)* status: all files reviewed, 11 unresolved discussions (waiting on @Eb-Zeero)

___
*[`frontend/src/components/exposure/ExposurePanel.tsx` line 216 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/75#-Nnnl9U7APKXHyMVKVzY:-Nnnl9U7APKXHyMVKVzZ:b-o9xhu0) ([raw file](https://github.com/saltastroops/nir-simulator/blob/2cced815aa9ab083442127de38091a68a507762c/frontend/src/components/exposure/ExposurePanel.tsx#L216)):*
> ```XML
>   return (
>     <div>
>       <div className="columns">
> ```

The Query fieldset has an overflow problem.

Rather use flex.
___
*[`frontend/src/components/exposure/gain-panel/GainPanel.tsx` line 97 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/75#-NnniZvw0sOn_KPPGMUT:-NnniZvw0sOn_KPPGMUU:b-6l4bi4) ([raw file](https://github.com/saltastroops/nir-simulator/blob/2cced815aa9ab083442127de38091a68a507762c/frontend/src/components/exposure/gain-panel/GainPanel.tsx#L97)):*
> ```XML
>     <div>
>       <div className="flex">
>         <div className="" style={{ minWidth: "160px" }}>
> ```

I don't think you need a minimum width here.
___
*[`frontend/src/components/exposure/gain-panel/NonEditableGainPanel.tsx` line 10 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/75#-Nnnj9hP3rMfEiiYJeqY:-Nnnj9hP3rMfEiiYJeqZ:btty5jr) ([raw file](https://github.com/saltastroops/nir-simulator/blob/2cced815aa9ab083442127de38091a68a507762c/frontend/src/components/exposure/gain-panel/NonEditableGainPanel.tsx#L10)):*
> ```XML
>   return (
>     <div>
>       <div className="flex" style={{ minWidth: "140px" }}>
> ```

Using flex doesn't gain you anything here, I think.
___
*[`frontend/src/components/exposure/gain-panel/NonEditableGainPanel.tsx` line 14 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/75#-NnnjIwN95NnQVCMK4by:-NnnjIwN95NnQVCMK4bz:btty5jr) ([raw file](https://github.com/saltastroops/nir-simulator/blob/2cced815aa9ab083442127de38091a68a507762c/frontend/src/components/exposure/gain-panel/NonEditableGainPanel.tsx#L14)):*
> ```XML
>         <div className="pl-2 ">{gain.gain} e/ADU</div>
>       </div>
>       <div className="flex">
> ```

Using flex doesn't gain you anything here, I think.
___
*[`frontend/src/components/exposure/gain-panel/NonEditableGainPanel.tsx` line 18 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/75#-NnnjKCH0y-16yo-kK4X:-NnnjKCH0y-16yo-kK4Y:btty5jr) ([raw file](https://github.com/saltastroops/nir-simulator/blob/2cced815aa9ab083442127de38091a68a507762c/frontend/src/components/exposure/gain-panel/NonEditableGainPanel.tsx#L18)):*
> ```XML
>         <div className="pl-2 "> {gain.readNoise}</div>
>       </div>
>       <div className="flex">
> ```

Using flex doesn't gain you anything here, I think.
___
*[`frontend/src/components/instrument/InstrumentConfigurationPanel.tsx` line 146 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/75#-NnnkwwV-rUuF-Gbgter:-NnnkwwV-rUuF-Gbgtes:b-5tgygz) ([raw file](https://github.com/saltastroops/nir-simulator/blob/2cced815aa9ab083442127de38091a68a507762c/frontend/src/components/instrument/InstrumentConfigurationPanel.tsx#L146)):*
> ```XML
>   return (
>     <div>
>       <div className="columns">
> ```

Rather use flex
___
*[`frontend/src/components/instrument/SpectroscopyConfigurationPanel.tsx` line 53 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/75#-NnnlJ4jCioezF5HFuxD:-NnnlJ4jCioezF5HFuxE:bsfq81c) ([raw file](https://github.com/saltastroops/nir-simulator/blob/2cced815aa9ab083442127de38091a68a507762c/frontend/src/components/instrument/SpectroscopyConfigurationPanel.tsx#L53)):*
> ```XML
>       <div className="field">
>         <div className="control pb-2">
>           <label>Grating</label>
> ```

It might be worth adding " (lines per mm)".
___
*[`frontend/src/components/plots/linePlot.css` line 3 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/75#-NnnlYE20hvrfTsEIWVa:-NnnlYE20hvrfTsEIWVb:b-tv9h2z) ([raw file](https://github.com/saltastroops/nir-simulator/blob/2cced815aa9ab083442127de38091a68a507762c/frontend/src/components/plots/linePlot.css#L3)):*
> ```CSS
> .chart-container {
>     position: relative;
>     width: 90%;
> ```

Might have to be tweaked.
___
*[`frontend/src/components/spectrum/BlackbodyPanel.tsx` line 92 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/75#-NnnluHB4jHmKLMk-TW_:-NnnluHB4jHmKLMk-TWa:b96q9z3) ([raw file](https://github.com/saltastroops/nir-simulator/blob/2cced815aa9ab083442127de38091a68a507762c/frontend/src/components/spectrum/BlackbodyPanel.tsx#L92)):*
> ```XML
>           <input
>             id={magnitudeId}
>             className={input("relative")}
> ```

Why the "relative"?
___
*[`frontend/src/components/spectrum/BlackbodyPanel.tsx` line 107 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/75#-Nnnlwe3CMKRkJxyggk1:-Nnnlwe3CMKRkJxyggk2:b96q9z3) ([raw file](https://github.com/saltastroops/nir-simulator/blob/2cced815aa9ab083442127de38091a68a507762c/frontend/src/components/spectrum/BlackbodyPanel.tsx#L107)):*
> ```XML
>           <input
>             id={temperatureId}
>             className={input("relative")}
> ```

Why the "relative"?
___
*[`frontend/src/components/spectrum/SpectrumGenerationTab.tsx` line 105 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/75#-NnnmjpfAcPpKrNOgixg:-NnnmjpfAcPpKrNOgixh:bwpqhch) ([raw file](https://github.com/saltastroops/nir-simulator/blob/2cced815aa9ab083442127de38091a68a507762c/frontend/src/components/spectrum/SpectrumGenerationTab.tsx#L105)):*
> ```XML
> 
>   return (
>     <div className="columns">
> ```

Rather use flex.

**Review by hettlage — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/nir-simulator/75)* status: all files reviewed, 12 unresolved discussions (waiting on @Eb-Zeero)

___
*[`frontend/src/components/spectrum/EmissionLinePanel.tsx` line 119 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/75#-Nnnt4gv4H3ubTKN84_9:-Nnnt4gv4H3ubTKN84_A:b-fjuq28) ([raw file](https://github.com/saltastroops/nir-simulator/blob/2cced815aa9ab083442127de38091a68a507762c/frontend/src/components/spectrum/EmissionLinePanel.tsx#L119)):*
> ```XML
>   const redshiftId = `redshift-${idCounter}`;
>   const fluxUnits =
>     sourceType == "Point" ? "erg/(cm² s)" : "erg/(cm² s arcsec²)";
> ```

The same distinction must be made in the plot of the source spectrum.

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/nir-simulator/75)* status: all files reviewed, 12 unresolved discussions (waiting on @hettlage)

___
*[`frontend/src/components/exposure/ExposurePanel.tsx` line 216 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/75#-Nnnl9U7APKXHyMVKVzY:-NnrKh7B-hxjcgdcir7J:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/2cced815aa9ab083442127de38091a68a507762c/frontend/src/components/exposure/ExposurePanel.tsx#L216)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The Query fieldset has an overflow problem.

Rather use flex.
</blockquote></details>

Done.
___
*[`frontend/src/components/exposure/gain-panel/GainPanel.tsx` line 97 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/75#-NnniZvw0sOn_KPPGMUT:-Nno1Dbh33WHPJ3EVyKD:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/2cced815aa9ab083442127de38091a68a507762c/frontend/src/components/exposure/gain-panel/GainPanel.tsx#L97)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think you need a minimum width here.
</blockquote></details>

Done.
___
*[`frontend/src/components/exposure/gain-panel/NonEditableGainPanel.tsx` line 10 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/75#-Nnnj9hP3rMfEiiYJeqY:-NnrKmEm7mQ7MAesCslB:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/2cced815aa9ab083442127de38091a68a507762c/frontend/src/components/exposure/gain-panel/NonEditableGainPanel.tsx#L10)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Using flex doesn't gain you anything here, I think.
</blockquote></details>

Done.
___
*[`frontend/src/components/exposure/gain-panel/NonEditableGainPanel.tsx` line 14 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/75#-NnnjIwN95NnQVCMK4by:-NnrKo4_-zDixet_WJOy:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/2cced815aa9ab083442127de38091a68a507762c/frontend/src/components/exposure/gain-panel/NonEditableGainPanel.tsx#L14)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Using flex doesn't gain you anything here, I think.
</blockquote></details>

Done.
___
*[`frontend/src/components/exposure/gain-panel/NonEditableGainPanel.tsx` line 18 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/75#-NnnjKCH0y-16yo-kK4X:-NnrKoj44YeZcbDEH1I-:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/2cced815aa9ab083442127de38091a68a507762c/frontend/src/components/exposure/gain-panel/NonEditableGainPanel.tsx#L18)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Using flex doesn't gain you anything here, I think.
</blockquote></details>

Done.
___
*[`frontend/src/components/instrument/InstrumentConfigurationPanel.tsx` line 146 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/75#-NnnkwwV-rUuF-Gbgter:-NnrKqcNEE8PpouyqIzH:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/2cced815aa9ab083442127de38091a68a507762c/frontend/src/components/instrument/InstrumentConfigurationPanel.tsx#L146)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Rather use flex
</blockquote></details>

Done.
___
*[`frontend/src/components/instrument/SpectroscopyConfigurationPanel.tsx` line 53 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/75#-NnnlJ4jCioezF5HFuxD:-NnrL8Jc5p4srfeh5HOd:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/2cced815aa9ab083442127de38091a68a507762c/frontend/src/components/instrument/SpectroscopyConfigurationPanel.tsx#L53)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It might be worth adding " (lines per mm)".
</blockquote></details>

Done.
___
*[`frontend/src/components/plots/linePlot.css` line 3 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/75#-NnnlYE20hvrfTsEIWVa:-NnrLAeg3Wd3E5sGCj9N:b-7ql1td) ([raw file](https://github.com/saltastroops/nir-simulator/blob/2cced815aa9ab083442127de38091a68a507762c/frontend/src/components/plots/linePlot.css#L3)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Might have to be tweaked.
</blockquote></details>

fixed
___
*[`frontend/src/components/spectrum/BlackbodyPanel.tsx` line 92 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/75#-NnnluHB4jHmKLMk-TW_:-NnrLYKZCLxrYDjWpEAo:b5qt3ax) ([raw file](https://github.com/saltastroops/nir-simulator/blob/2cced815aa9ab083442127de38091a68a507762c/frontend/src/components/spectrum/BlackbodyPanel.tsx#L92)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why the "relative"?
</blockquote></details>

maybe It was when showing you effects fixed now
___
*[`frontend/src/components/spectrum/BlackbodyPanel.tsx` line 107 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/75#-Nnnlwe3CMKRkJxyggk1:-NnrLewI4LrTqk808jHe:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/2cced815aa9ab083442127de38091a68a507762c/frontend/src/components/spectrum/BlackbodyPanel.tsx#L107)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why the "relative"?
</blockquote></details>

Done.
___
*[`frontend/src/components/spectrum/EmissionLinePanel.tsx` line 119 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/75#-Nnnt4gv4H3ubTKN84_9:-NnrU0e03M6Qwba5o_aX:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/2cced815aa9ab083442127de38091a68a507762c/frontend/src/components/spectrum/EmissionLinePanel.tsx#L119)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The same distinction must be made in the plot of the source spectrum.
</blockquote></details>

Done.
___
*[`frontend/src/components/spectrum/SpectrumGenerationTab.tsx` line 105 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/75#-NnnmjpfAcPpKrNOgixg:-Nns0STAC2cYm62yNDnl:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/2cced815aa9ab083442127de38091a68a507762c/frontend/src/components/spectrum/SpectrumGenerationTab.tsx#L105)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Rather use flex.
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/nir-simulator/75)* status: all files reviewed, 4 unresolved discussions (waiting on @Eb-Zeero)

___
*[`frontend/src/components/plots/linePlot.css` line 3 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/75#-NnnlYE20hvrfTsEIWVa:-Nnu04h_B5p98sfciX4T:b-uvc8d7) ([raw file](https://github.com/saltastroops/nir-simulator/blob/2cced815aa9ab083442127de38091a68a507762c/frontend/src/components/plots/linePlot.css#L3)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

fixed
</blockquote></details>

Choosing an absolute width and height means that the plots don't scale down properly when the window size decreases,
___
*[`frontend/src/components/spectrum/SpectrumGenerationTab.tsx` line 72 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/75#-Nnu1-yP7ZOGjU3I-eTH:-Nnu1-yP7ZOGjU3I-eTI:b-hqp1bb) ([raw file](https://github.com/saltastroops/nir-simulator/blob/62fc7f2274e57b77afbe27c43699929624a9ffbd/frontend/src/components/spectrum/SpectrumGenerationTab.tsx#L72)):*
> ```XML
>       const skyData = spectraData.sky;
>       const fluxUnits =
>         source.type == "Point" ? "erg/(cm² s)" : "erg/(cm² s arcsec²)";
> ```

Å is missing in the units.
___
*[`frontend/src/components/spectrum/SpectrumGenerationTab.tsx` line 80 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/75#-Nnu1Vmb2US_jQexvHI-:-Nnu1VmcBdR9oqRnxBxT:b-jyd111) ([raw file](https://github.com/saltastroops/nir-simulator/blob/62fc7f2274e57b77afbe27c43699929624a9ffbd/frontend/src/components/spectrum/SpectrumGenerationTab.tsx#L80)):*
> ```XML
>           lineColor: previousChartContent.chartData.lineColor,
>           options: defaultLinePlotOptions(
>             "Wavelength (\u212B)",
> ```

Can you use the actual character (Å) rather than the unicode (\u212B)?

(This obviously applies to other labels as well.)

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/nir-simulator/75)* status: 18 of 20 files reviewed, 4 unresolved discussions (waiting on @hettlage)

___
*[`frontend/src/components/plots/linePlot.css` line 3 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/75#-NnnlYE20hvrfTsEIWVa:-NnwZ-if1i0-fD5TJfOe:bb7f2mf) ([raw file](https://github.com/saltastroops/nir-simulator/blob/2cced815aa9ab083442127de38091a68a507762c/frontend/src/components/plots/linePlot.css#L3)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Choosing an absolute width and height means that the plots don't scale down properly when the window size decreases,
</blockquote></details>

done
___
*[`frontend/src/components/spectrum/SpectrumGenerationTab.tsx` line 72 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/75#-Nnu1-yP7ZOGjU3I-eTH:-NnxNG3_4XDkheJGsn8x:b-jmv0av) ([raw file](https://github.com/saltastroops/nir-simulator/blob/62fc7f2274e57b77afbe27c43699929624a9ffbd/frontend/src/components/spectrum/SpectrumGenerationTab.tsx#L72)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Å is missing in the units.
</blockquote></details>

double-check this Done.
___
*[`frontend/src/components/spectrum/SpectrumGenerationTab.tsx` line 80 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/75#-Nnu1Vmb2US_jQexvHI-:-NnwYsrh1Ub2QWhMgFPQ:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/62fc7f2274e57b77afbe27c43699929624a9ffbd/frontend/src/components/spectrum/SpectrumGenerationTab.tsx#L80)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Can you use the actual character (Å) rather than the unicode (\u212B)?

(This obviously applies to other labels as well.)
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/nir-simulator/75)* status: all files reviewed, 2 unresolved discussions (waiting on @Eb-Zeero)

___
*[`frontend/src/components/spectrum/SpectrumGenerationTab.tsx` line 99 at r4](https://reviewable.io/reviews/saltastroops/nir-simulator/75#-NoDtu3mEjQblhE8l2HY:-NoDtu3mEjQblhE8l2HZ:b4hrhdr) ([raw file](https://github.com/saltastroops/nir-simulator/blob/5d0b9ebd0a6e4e1f1ddf84f1e67e8b508dc99aa6/frontend/src/components/spectrum/SpectrumGenerationTab.tsx#L99)):*
> ```XML
>           options: defaultLinePlotOptions(
>             "Wavelength (Å)",
>             `Flux (${fluxUnits})`,
> ```

The sky spectrum is always per arcsec^2, irrespective of whether the source is a point source or a diffuse source.

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/nir-simulator/75)* status: 20 of 21 files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`frontend/src/components/spectrum/SpectrumGenerationTab.tsx` line 99 at r4](https://reviewable.io/reviews/saltastroops/nir-simulator/75#-NoDtu3mEjQblhE8l2HY:-NoGFykj26hIAjWB8vxl:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/5d0b9ebd0a6e4e1f1ddf84f1e67e8b508dc99aa6/frontend/src/components/spectrum/SpectrumGenerationTab.tsx#L99)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The sky spectrum is always per arcsec^2, irrespective of whether the source is a point source or a diffuse source.
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/nir-simulator/75)* status: all files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero)

___
*[`frontend/src/components/spectrum/SpectrumGenerationTab.tsx` line 97 at r5](https://reviewable.io/reviews/saltastroops/nir-simulator/75#-NoGLZXT4IbUMd5HYp2g:-NoGLZXT4IbUMd5HYp2h:b-cmrnn7) ([raw file](https://github.com/saltastroops/nir-simulator/blob/076a8ee80dbf7b8b8ef1d19ad414de91e48283f4/frontend/src/components/spectrum/SpectrumGenerationTab.tsx#L97)):*
> ```XML
>           y: skyData.fluxes,
>           lineColor: previousChartContent.chartData.lineColor,
>           options: previousChartContent.chartData.options,
> ```

When opening the Simulator, the ordinate labels for the source and sky plot now are inconsistent.

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/nir-simulator/75)* status: 20 of 21 files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`frontend/src/components/spectrum/SpectrumGenerationTab.tsx` line 97 at r5](https://reviewable.io/reviews/saltastroops/nir-simulator/75#-NoGLZXT4IbUMd5HYp2g:-NoGblzC4_hRkMvPyJvU:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/076a8ee80dbf7b8b8ef1d19ad414de91e48283f4/frontend/src/components/spectrum/SpectrumGenerationTab.tsx#L97)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

When opening the Simulator, the ordinate labels for the source and sky plot now are inconsistent.
</blockquote></details>

Done.

**Review by hettlage — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/nir-simulator/75)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Eb-Zeero)

**Pull request merged**
