### PR TITLE
Add sky background plot

### PR DESCRIPTION
**Pull request by mofokeng-chaka**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/nir-simulator/23)

### CODE REVIEW

**Review by Eb-Zeero — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/nir-simulator/23)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @mofokeng-chaka)

*[a discussion](https://reviewable.io/reviews/saltastroops/nir-simulator/23#-NjwzVni0QZZIg0wpd9I:-NjwzVni0QZZIg0wpd9J:b-pzbsxe) (no related file):*
if an error is raised error is never cleared. also, no error message is displayed
and, the plot will remain red until relaod

___
___
*[`react/src/components/spectrum/SpectrumGenerationTab.tsx` line 75 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/23#-NjwvIgDDh4SXkJxHvzL:-NjwvIgDDh4SXkJxHvzM:b-c1lxyk) ([raw file](https://github.com/saltastroops/nir-simulator/blob/aee6cc060aceb6d646dfd6f5d1ed927a4a756834/react/src/components/spectrum/SpectrumGenerationTab.tsx#L75)):*
> ```XML
>       const skyData = spectraData.sky;
> 
>       setChartContent((previousChartContent) => {
> ```

@hettlage 😁 might have a better name
setChartContent is very generic how about setSourcePlot or a better name showing that this is a source plot content
___
*[`react/src/components/spectrum/SpectrumGenerationTab.tsx` line 88 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/23#-Njww6TCDaj2qWwqSimZ:-Njww6TCDaj2qWwqSim_:b-7adcwb) ([raw file](https://github.com/saltastroops/nir-simulator/blob/aee6cc060aceb6d646dfd6f5d1ed927a4a756834/react/src/components/spectrum/SpectrumGenerationTab.tsx#L88)):*
> ```XML
>       });
> 
>       setSecondChartContent((previousChartContent) => {
> ```

setSecondChartContent is very generic how about setSkyPlot or a better name showing that this is a sky plot content
___
*[`react/src/components/spectrum/SpectrumGenerationTab.tsx` line 106 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/23#-Njwx0t09c3775goqiR-:-Njwx0t09c3775goqiR0:b2wtmm4) ([raw file](https://github.com/saltastroops/nir-simulator/blob/aee6cc060aceb6d646dfd6f5d1ed927a4a756834/react/src/components/spectrum/SpectrumGenerationTab.tsx#L106)):*
> ```XML
>   };
> 
>   const clearPlots = async () => {
> ```

this might be doing half the job
it should reset the form data as well
or easier add issue  and do all of this in a separate PR
___
*[`react/src/components/spectrum/SpectrumGenerationTab.tsx` line 107 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/23#-NjwxqJ4-flFby7dmDkp:-NjwxqJ4-flFby7dmDkq:b-xonecd) ([raw file](https://github.com/saltastroops/nir-simulator/blob/aee6cc060aceb6d646dfd6f5d1ed927a4a756834/react/src/components/spectrum/SpectrumGenerationTab.tsx#L107)):*
> ```XML
> 
>   const clearPlots = async () => {
>     try {
> ```

you will not need this try as you are not fetching this data from the API chance no need for async
___
*[`react/src/components/spectrum/SpectrumGenerationTab.tsx` line 187 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/23#-Njwy_M6AsOhi6p9TE9v:-Njwy_M6AsOhi6p9TE9w:b-dhmaxe) ([raw file](https://github.com/saltastroops/nir-simulator/blob/aee6cc060aceb6d646dfd6f5d1ed927a4a756834/react/src/components/spectrum/SpectrumGenerationTab.tsx#L187)):*
> ```XML
>             Show Spectrum
>           </button>
> ```

this buttons are ver close to each other maybe add some margin/padding
___
*[`react/src/components/spectrum/SpectrumGenerationTab.tsx` line 197 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/23#-NjwyuJx2dkpRxanc7_e:-NjwyuJx2dkpRxanc7_f:bjz1kk4) ([raw file](https://github.com/saltastroops/nir-simulator/blob/aee6cc060aceb6d646dfd6f5d1ed927a4a756834/react/src/components/spectrum/SpectrumGenerationTab.tsx#L197)):*
> ```XML
>       </div>
>       <div className="column">
>         <div className="bg-gray-50">
> ```

plot needs some heading/ title
___
*[`react/src/components/spectrum/SpectrumGenerationTab.tsx` line 203 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/23#-Njwz0hk2ObUxpjVzxHs:-Njwz0hk2ObUxpjVzxHt:bjz1kk4) ([raw file](https://github.com/saltastroops/nir-simulator/blob/aee6cc060aceb6d646dfd6f5d1ed927a4a756834/react/src/components/spectrum/SpectrumGenerationTab.tsx#L203)):*
> ```XML
>         </div>
>         <div className="bg-gray-50 mt-2">
>           <div className={!error ? "tile" : "tile notification is-danger"}>
> ```

plot needs some heading/ title

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/nir-simulator/23)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

*[a discussion](https://reviewable.io/reviews/saltastroops/nir-simulator/23#-NjwzVni0QZZIg0wpd9I:-Nk00XvZEfOgWpVOSalS:b-inr0hi) (no related file):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

if an error is raised error is never cleared. also, no error message is displayed
and, the plot will remain red until relaod
</blockquote></details>

Now the error message disappears when you press the button.

___
___
*[`react/src/components/spectrum/SpectrumGenerationTab.tsx` line 75 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/23#-NjwvIgDDh4SXkJxHvzL:-Nk-Cl7B47ucOikiJjPg:b-o9q55g) ([raw file](https://github.com/saltastroops/nir-simulator/blob/aee6cc060aceb6d646dfd6f5d1ed927a4a756834/react/src/components/spectrum/SpectrumGenerationTab.tsx#L75)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

@hettlage 😁 might have a better name
setChartContent is very generic how about setSourcePlot or a better name showing that this is a source plot content
</blockquote></details>

I have renamed it to `setSourceChartContent`.
___
*[`react/src/components/spectrum/SpectrumGenerationTab.tsx` line 88 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/23#-Njww6TCDaj2qWwqSimZ:-Nk-CvIX2gON4X4dsFbd:b8pfs5j) ([raw file](https://github.com/saltastroops/nir-simulator/blob/aee6cc060aceb6d646dfd6f5d1ed927a4a756834/react/src/components/spectrum/SpectrumGenerationTab.tsx#L88)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

setSecondChartContent is very generic how about setSkyPlot or a better name showing that this is a sky plot content
</blockquote></details>

I have renamed to `setSkyChartContent`. 
___
*[`react/src/components/spectrum/SpectrumGenerationTab.tsx` line 106 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/23#-Njwx0t09c3775goqiR-:-Nk-usAA40Jm78T74Gim:bfovv0t) ([raw file](https://github.com/saltastroops/nir-simulator/blob/aee6cc060aceb6d646dfd6f5d1ed927a4a756834/react/src/components/spectrum/SpectrumGenerationTab.tsx#L106)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

this might be doing half the job
it should reset the form data as well
or easier add issue  and do all of this in a separate PR
</blockquote></details>

As per our agreement, the button is now removed.
___
*[`react/src/components/spectrum/SpectrumGenerationTab.tsx` line 107 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/23#-NjwxqJ4-flFby7dmDkp:-Nk-DBzE4SqLt8mXUXGC:b-zhc10g) ([raw file](https://github.com/saltastroops/nir-simulator/blob/aee6cc060aceb6d646dfd6f5d1ed927a4a756834/react/src/components/spectrum/SpectrumGenerationTab.tsx#L107)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

you will not need this try as you are not fetching this data from the API chance no need for async
</blockquote></details>

Well spotted, thanks!
___
*[`react/src/components/spectrum/SpectrumGenerationTab.tsx` line 187 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/23#-Njwy_M6AsOhi6p9TE9v:-Nk-ELZe3eeTEzQ0pag_:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/aee6cc060aceb6d646dfd6f5d1ed927a4a756834/react/src/components/spectrum/SpectrumGenerationTab.tsx#L187)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

this buttons are ver close to each other maybe add some margin/padding
</blockquote></details>

Done.
___
*[`react/src/components/spectrum/SpectrumGenerationTab.tsx` line 197 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/23#-NjwyuJx2dkpRxanc7_e:-Nk-tVlkB7GVIHbJOeMK:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/aee6cc060aceb6d646dfd6f5d1ed927a4a756834/react/src/components/spectrum/SpectrumGenerationTab.tsx#L197)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

plot needs some heading/ title
</blockquote></details>

Done.
___
*[`react/src/components/spectrum/SpectrumGenerationTab.tsx` line 203 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/23#-Njwz0hk2ObUxpjVzxHs:-Nk-tVFj68mwJEHkjoEq:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/aee6cc060aceb6d646dfd6f5d1ed927a4a756834/react/src/components/spectrum/SpectrumGenerationTab.tsx#L203)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

plot needs some heading/ title
</blockquote></details>

Done.

**Review by Eb-Zeero — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/nir-simulator/23)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mofokeng-chaka)

**Review by Eb-Zeero — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/nir-simulator/23)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mofokeng-chaka)

**Pull request merged**
