### PR TITLE
Add spectrum calculations and plots

### PR DESCRIPTION
**Pull request by mofokeng-chaka**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/nir-simulator/13)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/nir-simulator/13)* status: all files reviewed, 7 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`backend/nirwals/views.py` line 40 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/13#-NhzU76jE7aGOXdshkcJ:-NhzU76jE7aGOXdshkcK:bgfxema) ([raw file](https://github.com/saltastroops/nir-simulator/blob/5247d7a34dae04686288332106ce1bc5631c53a2/backend/nirwals/views.py#L40)):*
> ```Python
> def spectra(request):
>     parameters = json.loads(request.POST.get("data"))
>     seeing = float(parameters["earth"]["seeing"])
> ```

The `seeing = ...` line seems superfluous...
___
*[`backend/nirwals/views.py` line 41 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/13#-NhzfaJHCp7kt0Pjv0i1:-NhzfaJHCp7kt0Pjv0i2:b-1t9mqd) ([raw file](https://github.com/saltastroops/nir-simulator/blob/5247d7a34dae04686288332106ce1bc5631c53a2/backend/nirwals/views.py#L41)):*
> ```Python
>     parameters = json.loads(request.POST.get("data"))
>     seeing = float(parameters["earth"]["seeing"])
>     wavelength, sources_flux_values = get_sources_spectrum(parameters)
> ```

That might be a minor issue, but shouldn't the background either be called "background" or "sky", but not both? (I guess "sky" might be slightly more accurate, as "background " might include cosmic rays etc.)
___
*[`backend/nirwals/configure/data/spectrum.py` line 31 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/13#-NhzgAzsDWPx_C_Jqtmd:-NhzgAzsDWPx_C_Jqtme:b8tgmby) ([raw file](https://github.com/saltastroops/nir-simulator/blob/5247d7a34dae04686288332106ce1bc5631c53a2/backend/nirwals/configure/data/spectrum.py#L31)):*
> ```Python
>     normalized_star_radiation = star_black_body_radiation/normalizer
>     photon_count = (normalized_star_radiation / ((h * c) / wavelength))
>     flux = flux + photon_count
> ```

Why do you need the `flux` variable?

(The same question applies to other functions as well.)
___
*[`backend/nirwals/configure/data/spectrum.py` line 48 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/13#-Nhzh5C52LHJ28tSadvL:-Nhzh5C52LHJ28tSadvM:b-t9d2yv) ([raw file](https://github.com/saltastroops/nir-simulator/blob/5247d7a34dae04686288332106ce1bc5631c53a2/backend/nirwals/configure/data/spectrum.py#L48)):*
> ```Python
>         galaxy_flux = galaxy_flux / (1 + redshift)
> 
>         starting_index = np.nonzero(np.isin(wavelength, galaxy_wavelength))[0][0]
> ```

Can we discuss the redshift calculation?
___
*[`backend/nirwals/configure/data/spectrum.py` line 67 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/13#-NhzhAzHAGYtIZ9CrSsN:-NhzhAzHAGYtIZ9CrSsO:beg7h38) ([raw file](https://github.com/saltastroops/nir-simulator/blob/5247d7a34dae04686288332106ce1bc5631c53a2/backend/nirwals/configure/data/spectrum.py#L67)):*
> ```Python
>     line_profile = line_flux * 1 / (line_signal * np.sqrt(2 * np.pi)) * np.exp(-((wavelength - central_wavelength) ** 2 / (2 * line_signal**2)))
> 
>     flux = flux + line_profile / ((h * c) / wavelength)
> ```

What about redshift?
___
*[`react/src/components/spectrum/SpectrumGenerationTab.tsx` line 33 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/13#-Ni-SJ0kBrIDzgQjUJTR:-Ni-SJ0l3IYh4Yn4i-Da:b-nghblb) ([raw file](https://github.com/saltastroops/nir-simulator/blob/5247d7a34dae04686288332106ce1bc5631c53a2/react/src/components/spectrum/SpectrumGenerationTab.tsx#L33)):*
> ```XML
>         requested: false,
>     });
>     const [error, ] = useState<string | null>(null);
> ```

You are missing a `setError` function here.
___
*[`react/src/components/spectrum/SpectrumGenerationTab.tsx` line 45 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/13#-Ni-SRvOAEzL07cxc1dr:-Ni-SRvOAEzL07cxc1ds:b-qy66ud) ([raw file](https://github.com/saltastroops/nir-simulator/blob/5247d7a34dae04686288332106ce1bc5631c53a2/react/src/components/spectrum/SpectrumGenerationTab.tsx#L45)):*
> ```XML
> 
>   const updatePlots = async () => {
>     const spectraData = await spectra(setup);
> ```

Errors aren't handled.

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/nir-simulator/13)* status: all files reviewed, 7 unresolved discussions (waiting on @hettlage)

___
*[`backend/nirwals/views.py` line 40 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/13#-NhzU76jE7aGOXdshkcJ:-Ni-lk8u2GdBfdBVacVD:b-5qf909) ([raw file](https://github.com/saltastroops/nir-simulator/blob/5247d7a34dae04686288332106ce1bc5631c53a2/backend/nirwals/views.py#L40)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The `seeing = ...` line seems superfluous...
</blockquote></details>

I have removed it.
___
*[`backend/nirwals/views.py` line 41 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/13#-NhzfaJHCp7kt0Pjv0i1:-Ni-m8B70gv9_NcbQKCM:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/5247d7a34dae04686288332106ce1bc5631c53a2/backend/nirwals/views.py#L41)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

That might be a minor issue, but shouldn't the background either be called "background" or "sky", but not both? (I guess "sky" might be slightly more accurate, as "background " might include cosmic rays etc.)
</blockquote></details>

Done.
___
*[`backend/nirwals/configure/data/spectrum.py` line 31 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/13#-NhzgAzsDWPx_C_Jqtmd:-Ni-m9sB1tYP123400YV:b78dpod) ([raw file](https://github.com/saltastroops/nir-simulator/blob/5247d7a34dae04686288332106ce1bc5631c53a2/backend/nirwals/configure/data/spectrum.py#L31)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why do you need the `flux` variable?

(The same question applies to other functions as well.)
</blockquote></details>

Not needed, I have removed the variables accordingly.
___
*[`backend/nirwals/configure/data/spectrum.py` line 48 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/13#-Nhzh5C52LHJ28tSadvL:-Ni-mr1YEr6UaZdWTstH:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/5247d7a34dae04686288332106ce1bc5631c53a2/backend/nirwals/configure/data/spectrum.py#L48)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Can we discuss the redshift calculation?
</blockquote></details>

Done.
___
*[`backend/nirwals/configure/data/spectrum.py` line 67 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/13#-NhzhAzHAGYtIZ9CrSsN:-Ni-uam037pVLSQbLohu:b-1lznnl) ([raw file](https://github.com/saltastroops/nir-simulator/blob/5247d7a34dae04686288332106ce1bc5631c53a2/backend/nirwals/configure/data/spectrum.py#L67)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

What about redshift?
</blockquote></details>

Now included in the calculations
___
*[`react/src/components/spectrum/SpectrumGenerationTab.tsx` line 33 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/13#-Ni-SJ0kBrIDzgQjUJTR:-Ni3bkVa5CWlXU2qoZgE:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/5247d7a34dae04686288332106ce1bc5631c53a2/react/src/components/spectrum/SpectrumGenerationTab.tsx#L33)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You are missing a `setError` function here.
</blockquote></details>

Done.
___
*[`react/src/components/spectrum/SpectrumGenerationTab.tsx` line 45 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/13#-Ni-SRvOAEzL07cxc1dr:-Ni3bitD1zFqJTKnAYHn:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/5247d7a34dae04686288332106ce1bc5631c53a2/react/src/components/spectrum/SpectrumGenerationTab.tsx#L45)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Errors aren't handled.
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/nir-simulator/13)* status: all files reviewed, 4 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`backend/nirwals/configure/data/spectrum.py` line 9 at r3](https://reviewable.io/reviews/saltastroops/nir-simulator/13#-Ni4UetMATIHLdr9P_db:-Ni4UetNEhLFZVfsw_-S:bcknxld) ([raw file](https://github.com/saltastroops/nir-simulator/blob/d1aaef3e6095a8f705db055a52acefc599f559b3/backend/nirwals/configure/data/spectrum.py#L9)):*
> ```Python
> from specutils import Spectrum1D
> from specutils.manipulation import FluxConservingResampler
> from astropy import units as u
> ```

Something to do when having another look at the backend: Use AstroPy units throughout.
___
*[`backend/nirwals/configure/data/spectrum.py` line 30 at r3](https://reviewable.io/reviews/saltastroops/nir-simulator/13#-Ni4V5Ko3Fk-aXBh3Prx:-Ni4V5Ko3Fk-aXBh3Pry:b-6ikejg) ([raw file](https://github.com/saltastroops/nir-simulator/blob/d1aaef3e6095a8f705db055a52acefc599f559b3/backend/nirwals/configure/data/spectrum.py#L30)):*
> ```Python
> 
>     star_magnitude_flux = 3.02 * 10 ** (-10) * 10 ** (-0.4 * mag)
>     normalizer = max(star_black_body_radiation) / star_magnitude_flux
> ```

Are you sure that using the maximum value is correct?

(And what magnitude is mag, i.e.what is the bandpass?)
___
*[`backend/nirwals/configure/data/spectrum.py` line 52 at r3](https://reviewable.io/reviews/saltastroops/nir-simulator/13#-Ni4VZng4cpahFkzBrqD:-Ni4VZng4cpahFkzBrqE:b-ppqiir) ([raw file](https://github.com/saltastroops/nir-simulator/blob/d1aaef3e6095a8f705db055a52acefc599f559b3/backend/nirwals/configure/data/spectrum.py#L52)):*
> ```Python
>         input_spectrum = Spectrum1D(spectral_axis=input_wavelength, flux=input_flux)
> 
>         fluxcon = FluxConservingResampler()
> ```

Wouldn't you rather call this something like `resampler`?
___
*[`backend/nirwals/configure/data/spectrum.py` line 60 at r3](https://reviewable.io/reviews/saltastroops/nir-simulator/13#-Ni4VuQl6fHBD5G_YIv5:-Ni4VuQl6fHBD5G_YIv6:b-6ikejg) ([raw file](https://github.com/saltastroops/nir-simulator/blob/d1aaef3e6095a8f705db055a52acefc599f559b3/backend/nirwals/configure/data/spectrum.py#L60)):*
> ```Python
>         galaxy_magnitude_flux = 3.02 * 10 ** (-10) * 10 ** (-0.4 * magnitude)
> 
>         normalizer = max(new_resampled_spectrum.flux) / galaxy_magnitude_flux
> ```

Are you sure that using the maximum value is correct?

(And what magnitude is mag, i.e.what is the bandpass?)

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/nir-simulator/13)* status: all files reviewed, 4 unresolved discussions (waiting on @hettlage)

___
*[`backend/nirwals/configure/data/spectrum.py` line 9 at r3](https://reviewable.io/reviews/saltastroops/nir-simulator/13#-Ni4UetMATIHLdr9P_db:-Ni4ZSgw7i5GimNhUnb9:bwvzt7d) ([raw file](https://github.com/saltastroops/nir-simulator/blob/d1aaef3e6095a8f705db055a52acefc599f559b3/backend/nirwals/configure/data/spectrum.py#L9)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Something to do when having another look at the backend: Use AstroPy units throughout.
</blockquote></details>

I have opened a new issue for this comment.
___
*[`backend/nirwals/configure/data/spectrum.py` line 30 at r3](https://reviewable.io/reviews/saltastroops/nir-simulator/13#-Ni4V5Ko3Fk-aXBh3Prx:-Ni4ZAazCQQYMgnxG-X1:bwvzt7d) ([raw file](https://github.com/saltastroops/nir-simulator/blob/d1aaef3e6095a8f705db055a52acefc599f559b3/backend/nirwals/configure/data/spectrum.py#L30)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Are you sure that using the maximum value is correct?

(And what magnitude is mag, i.e.what is the bandpass?)
</blockquote></details>

I have opened a new issue for this comment.
___
*[`backend/nirwals/configure/data/spectrum.py` line 52 at r3](https://reviewable.io/reviews/saltastroops/nir-simulator/13#-Ni4VZng4cpahFkzBrqD:-Ni4XIHp9QQjY_wxAlVc:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/d1aaef3e6095a8f705db055a52acefc599f559b3/backend/nirwals/configure/data/spectrum.py#L52)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Wouldn't you rather call this something like `resampler`?
</blockquote></details>

Done.
___
*[`backend/nirwals/configure/data/spectrum.py` line 60 at r3](https://reviewable.io/reviews/saltastroops/nir-simulator/13#-Ni4VuQl6fHBD5G_YIv5:-Ni4Z5uJBwyICovREzMP:bwvzt7d) ([raw file](https://github.com/saltastroops/nir-simulator/blob/d1aaef3e6095a8f705db055a52acefc599f559b3/backend/nirwals/configure/data/spectrum.py#L60)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Are you sure that using the maximum value is correct?

(And what magnitude is mag, i.e.what is the bandpass?)
</blockquote></details>

I have opened a new issue for this comment.

**Review by hettlage — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/nir-simulator/13)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mofokeng-chaka)

**Pull request merged**
