### PR TITLE
Configuration tab

### PR DESCRIPTION
**Pull request by Eb-Zeero**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/nir-simulator/5)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 20 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/nir-simulator/5)* status: all files reviewed, 22 unresolved discussions (waiting on @Eb-Zeero)

___
*[`backend/backend/urls.py` line 16 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/5#-Ngwj-ul4ybCsvJzlOie:-Ngwj-ul4ybCsvJzlOif:b-1juq7i) ([raw file](https://github.com/saltastroops/nir-simulator/blob/ae7efabe2e8dd6b49cc9a0e66ed1b11b9a3c2ac3/backend/backend/urls.py#L16)):*
> ```Python
>     path("", home, name="home"),
>     path("__reload__/", include("django_browser_reload.urls")),
>     path("throughput/", throughput, name='throughput')
> ```

Can we discuss the overall project structure?
___
*[`backend/backend/modules/__init__.py` line 0 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/5#-NgwaP68-3JTz48gg3us:-NgwaP68-3JTz48gg3ut:b-xaqpqp) ([raw file](https://github.com/saltastroops/nir-simulator/blob/67c841d672a0831041df43b5b8a0b743182c5cf7/backend/backend/modules/__init__.py#L0)):*
Why the name `modules`?
___
*[`backend/backend/modules/throughput.py` line 2 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/5#-NgwdNrH77iq5XAtqCtR:-NgwdNrH77iq5XAtqCtS:b-1sa8he) ([raw file](https://github.com/saltastroops/nir-simulator/blob/ae7efabe2e8dd6b49cc9a0e66ed1b11b9a3c2ac3/backend/backend/modules/throughput.py#L2)):*
> ```Python
> class ThroughputSpectra:
>     def __init__(self):
> ```

Can't this be done more effectively with NumPy?
___
*[`backend/backend/modules/throughput.py` line 7 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/5#-NgwdUj9Al13DYVUDZPy:-NgwdUj9Al13DYVUDZPz:b-yp3qlt) ([raw file](https://github.com/saltastroops/nir-simulator/blob/ae7efabe2e8dd6b49cc9a0e66ed1b11b9a3c2ac3/backend/backend/modules/throughput.py#L7)):*
> ```Python
>         self.spectra = []
>         self.modified_spectra = self.spectra
>         for i in range(40001):
> ```

You construct the array of x values multiple times in the code it seems. At the very least, the "magic" number 40001 appears multiple times. There should be a single source of truth for this.
___
*[`backend/backend/modules/data/throughput.py` line 6 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/5#-Ngwc5RM7ZyZBYk9yoAg:-Ngwc5RM7ZyZBYk9yoAh:b-67o86f) ([raw file](https://github.com/saltastroops/nir-simulator/blob/ae7efabe2e8dd6b49cc9a0e66ed1b11b9a3c2ac3/backend/backend/modules/data/throughput.py#L6)):*
> ```Python
> from scipy.special import erf
> 
> ZA = 31  # This value should be set globally.
> ```

And what _is_ the value?
___
*[`backend/backend/modules/data/throughput.py` line 21 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/5#-Ngwajq4EGunIDM6hrHV:-Ngwajq4EGunIDM6hrHW:bsn7s3q) ([raw file](https://github.com/saltastroops/nir-simulator/blob/ae7efabe2e8dd6b49cc9a0e66ed1b11b9a3c2ac3/backend/backend/modules/data/throughput.py#L21)):*
> ```Python
> def get_slit_modifier(constant):
>     num_points = 40001
>     wavelength = np.arange(9000, 9000 + num_points / 5, 1 / 5)
> ```

`np.linspace` might be the easier option?

(The same applies to other uses of `np.arange`.)
___
*[`backend/backend/modules/data/throughput.py` line 24 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/5#-NgwbXtW0FuubfRqkVAD:-NgwbXtX5mUStAcFo2m8:b-gq41c6) ([raw file](https://github.com/saltastroops/nir-simulator/blob/ae7efabe2e8dd6b49cc9a0e66ed1b11b9a3c2ac3/backend/backend/modules/data/throughput.py#L24)):*
> ```Python
>     modifier = np.full(num_points, constant, dtype=float)
>     return wavelength, modifier
> ```

General remark: This looks as if you are reading in the files every time a request is made, which is presumably ineffective. Caching might be a good choice here.
___
*[`backend/backend/modules/data/throughput.py` line 46 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/5#-NgwjVTQ-fmhOlsHHuno:-NgwjVTQ-fmhOlsHHunp:b-ce3vf5) ([raw file](https://github.com/saltastroops/nir-simulator/blob/ae7efabe2e8dd6b49cc9a0e66ed1b11b9a3c2ac3/backend/backend/modules/data/throughput.py#L46)):*
> ```Python
> 
> 
> def get_modifiers(form_data):
> ```

Can we discuss the way the data is handled?
___
*[`backend/backend/views/throughput.py` line 18 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/5#-NgwfeKb2DUNaERZqkkr:-NgwfeKb2DUNaERZqkks:b-5kx5oq) ([raw file](https://github.com/saltastroops/nir-simulator/blob/ae7efabe2e8dd6b49cc9a0e66ed1b11b9a3c2ac3/backend/backend/views/throughput.py#L18)):*
> ```Python
>     }
> 
>     if request.method == "POST":
> ```

In the absence of a proper REST framework used, maybe you should just assume a POST request. (In particular because the code doesn't seem to handle non-POST requests properly. (They may not fail, but they may also not do what the user expects, as their configuration details won't be used.)
___
*[`backend/backend/views/throughput.py` line 22 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/5#-NgwfQvM9uXP3rZkygbU:-NgwfQvM9uXP3rZkygbV:b-l864ee) ([raw file](https://github.com/saltastroops/nir-simulator/blob/ae7efabe2e8dd6b49cc9a0e66ed1b11b9a3c2ac3/backend/backend/views/throughput.py#L22)):*
> ```Python
>         post_data = request.POST
>         for key in default_options:
>             default_options[key] = post_data.get(key, default_options[key])
> ```

From here on, the "default_options" are no default options any longer...
___
*[`react/src/App.jsx` line 5 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/5#-Ngwgpzz99wGsy_-S0qG:-Ngwgpzz99wGsy_-S0qH:by5droh) ([raw file](https://github.com/saltastroops/nir-simulator/blob/ae7efabe2e8dd6b49cc9a0e66ed1b11b9a3c2ac3/react/src/App.jsx#L5)):*
> ```JavaScript
> 
> function App() {
>     // Register the plugin to all charts:
> ```

// Register the controllers and elements for the charts
___
*[`react/src/components/configure/TelescopeConfigure.css` line 2 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/5#-NgwjJBQ4coU4zxqMtCb:-NgwjJBQ4coU4zxqMtCc:b-wnyv98) ([raw file](https://github.com/saltastroops/nir-simulator/blob/ae7efabe2e8dd6b49cc9a0e66ed1b11b9a3c2ac3/react/src/components/configure/TelescopeConfigure.css#L2)):*
> ```CSS
> 
> select {
> ```

Can we discuss this?
___
*[`react/src/components/configure/TelescopeConfigure.jsx` line 1 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/5#-NgwhnrA3DXkUdZRSV4W:-NgwhnrA3DXkUdZRSV4X:b-tysi1s) ([raw file](https://github.com/saltastroops/nir-simulator/blob/ae7efabe2e8dd6b49cc9a0e66ed1b11b9a3c2ac3/react/src/components/configure/TelescopeConfigure.jsx#L1)):*
> ```JavaScript
> import {useState} from "react";
> ```

Should be reviewed and modified after PR #7 has been merged.
___
*[`react/src/components/configure/TelescopeConfigure.jsx` line 64 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/5#-NgwhUuWE3mMHFEq6b_k:-NgwhUuWE3mMHFEq6b_l:b-rdx0xi) ([raw file](https://github.com/saltastroops/nir-simulator/blob/ae7efabe2e8dd6b49cc9a0e66ed1b11b9a3c2ac3/react/src/components/configure/TelescopeConfigure.jsx#L64)):*
> ```JavaScript
>         }
> 
>         fetch('http://127.0.0.1:8000/throughput/', {
> ```

The URL should not be hardcoded.
___
*[`react/src/components/configure/TelescopeConfigure.jsx` line 83 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/5#-NgwlleW-9ORjtnb_Z_T:-NgwlleW-9ORjtnb_Z_U:bmxz78r) ([raw file](https://github.com/saltastroops/nir-simulator/blob/ae7efabe2e8dd6b49cc9a0e66ed1b11b9a3c2ac3/react/src/components/configure/TelescopeConfigure.jsx#L83)):*
> ```JavaScript
>             const newData = {
>                 labels: data.x,
>                 datasets: [
> ```

Shouldn't this be defined in the plot class?
___
*[`react/src/components/configure/TelescopeConfigure.jsx` line 104 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/5#-NgwlSTI9HAyywcBrlcw:-NgwlSTJ24kMU6OrpA0H:b5tb35c) ([raw file](https://github.com/saltastroops/nir-simulator/blob/ae7efabe2e8dd6b49cc9a0e66ed1b11b9a3c2ac3/react/src/components/configure/TelescopeConfigure.jsx#L104)):*
> ```JavaScript
> 
>     return (
>         <div className="container">
> ```

This is a long piece of code, and splitting it up into different pieces might make it more readable.
___
*[`react/src/components/exposure/MakeAnExposure.jsx` line 1 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/5#-Ngwi1_sCIwQ8ijJL8uj:-Ngwi1_t5b9TrhESi0ti:bc1bc31) ([raw file](https://github.com/saltastroops/nir-simulator/blob/ae7efabe2e8dd6b49cc9a0e66ed1b11b9a3c2ac3/react/src/components/exposure/MakeAnExposure.jsx#L1)):*
> ```JavaScript
> import {useState} from "react";
> ```

Should be reviewed ands modified after PR #7 has been merged.
___
*[`react/src/components/general-spectra/GeneralSpectra.jsx` line 2 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/5#-Ngwi4po4thXEvyGDYN4:-Ngwi4po4thXEvyGDYN5:bc1bc31) ([raw file](https://github.com/saltastroops/nir-simulator/blob/ae7efabe2e8dd6b49cc9a0e66ed1b11b9a3c2ac3/react/src/components/general-spectra/GeneralSpectra.jsx#L2)):*
> ```JavaScript
> import {useState} from "react";
> ```

Should be reviewed ands modified after PR #7 has been merged.
___
*[`react/src/components/plots/LinePlot.jsx` line 1 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/5#-Ngwkbyo6-8IVXjCRPfU:-Ngwkbyo6-8IVXjCRPfV:b-mjvygc) ([raw file](https://github.com/saltastroops/nir-simulator/blob/ae7efabe2e8dd6b49cc9a0e66ed1b11b9a3c2ac3/react/src/components/plots/LinePlot.jsx#L1)):*
> ```JavaScript
> import './linePlot.css';
> ```

The name "LinePlot" is misleading, as this is a throughput plot, not a general line plot.
___
*[`react/src/components/plots/LinePlot.jsx` line 16 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/5#-Ngwjei48bkY2SQ6nOnS:-Ngwjei48bkY2SQ6nOnT:b-6wnizm) ([raw file](https://github.com/saltastroops/nir-simulator/blob/ae7efabe2e8dd6b49cc9a0e66ed1b11b9a3c2ac3/react/src/components/plots/LinePlot.jsx#L16)):*
> ```JavaScript
>                     min: 8000,
>                     max: 18000,
>                     stepSize: 1000 // <----- This prop sets the stepSize
> ```

Isn't the comment a bit redundant? :-)
___
*[`react/src/components/plots/LinePlot.jsx` line 29 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/5#-NgwkAzD5lsXiVOZ4v2F:-NgwkAzD5lsXiVOZ4v2G:b-hqry32) ([raw file](https://github.com/saltastroops/nir-simulator/blob/ae7efabe2e8dd6b49cc9a0e66ed1b11b9a3c2ac3/react/src/components/plots/LinePlot.jsx#L29)):*
> ```JavaScript
>         },
>         pan: {
>             enabled: true
> ```

Why do you enable panning?
___
*[`react/src/components/plots/linePlot.css` line 1 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/5#-NgwiH7K1NdZRhVrKhgc:-NgwiH7K1NdZRhVrKhgd:ba6h9ye) ([raw file](https://github.com/saltastroops/nir-simulator/blob/ae7efabe2e8dd6b49cc9a0e66ed1b11b9a3c2ac3/react/src/components/plots/linePlot.css#L1)):*
> ```CSS
> .chart-container {
> ```

Can we discuss this, please?

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/nir-simulator/5)* status: all files reviewed, 22 unresolved discussions (waiting on @hettlage)

___
*[`backend/backend/urls.py` line 16 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/5#-Ngwj-ul4ybCsvJzlOie:-Nh0W2bJ6nWMaq5-OBHH:b-rgub6) ([raw file](https://github.com/saltastroops/nir-simulator/blob/ae7efabe2e8dd6b49cc9a0e66ed1b11b9a3c2ac3/backend/backend/urls.py#L16)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Can we discuss the overall project structure?
</blockquote></details>

views be fixed on another PR
___
*[`backend/backend/modules/__init__.py` line  at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/5#-NgwaP68-3JTz48gg3us:-Nh0Wp929sp2XFhFb4uX:b32afwg) ([raw file](https://github.com/saltastroops/nir-simulator/blob/67c841d672a0831041df43b5b8a0b743182c5cf7/backend/backend/modules/__init__.py#L)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why the name `modules`?
</blockquote></details>

renamed to configure
___
*[`backend/backend/modules/throughput.py` line 2 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/5#-NgwdNrH77iq5XAtqCtR:-Nh1PNuf4Y4sD4jvuRnH:byq868l) ([raw file](https://github.com/saltastroops/nir-simulator/blob/ae7efabe2e8dd6b49cc9a0e66ed1b11b9a3c2ac3/backend/backend/modules/throughput.py#L2)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Can't this be done more effectively with NumPy?
</blockquote></details>

will open an issue in dealing with efficiency 
___
*[`backend/backend/modules/throughput.py` line 7 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/5#-NgwdUj9Al13DYVUDZPy:-Nh1PYq--klTi8w39If0:byq868l) ([raw file](https://github.com/saltastroops/nir-simulator/blob/ae7efabe2e8dd6b49cc9a0e66ed1b11b9a3c2ac3/backend/backend/modules/throughput.py#L7)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You construct the array of x values multiple times in the code it seems. At the very least, the "magic" number 40001 appears multiple times. There should be a single source of truth for this.
</blockquote></details>

will open an issue in dealing with efficiency 
___
*[`backend/backend/modules/data/throughput.py` line 6 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/5#-Ngwc5RM7ZyZBYk9yoAg:-Nh0YzZQ4--00AqPVG7s:b-265ikb) ([raw file](https://github.com/saltastroops/nir-simulator/blob/ae7efabe2e8dd6b49cc9a0e66ed1b11b9a3c2ac3/backend/backend/modules/data/throughput.py#L6)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

And what _is_ the value?
</blockquote></details>

fixed now
___
*[`backend/backend/modules/data/throughput.py` line 21 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/5#-Ngwajq4EGunIDM6hrHV:-Nh0c57h7iqX19_cOgux:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/ae7efabe2e8dd6b49cc9a0e66ed1b11b9a3c2ac3/backend/backend/modules/data/throughput.py#L21)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

`np.linspace` might be the easier option?

(The same applies to other uses of `np.arange`.)
</blockquote></details>

Done.
___
*[`backend/backend/modules/data/throughput.py` line 24 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/5#-NgwbXtW0FuubfRqkVAD:-Nh0rqSwDAPOqTBaWx4j:b-72i9wa) ([raw file](https://github.com/saltastroops/nir-simulator/blob/ae7efabe2e8dd6b49cc9a0e66ed1b11b9a3c2ac3/backend/backend/modules/data/throughput.py#L24)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

General remark: This looks as if you are reading in the files every time a request is made, which is presumably ineffective. Caching might be a good choice here.
</blockquote></details>

will address this separately on a different PR
___
*[`backend/backend/modules/data/throughput.py` line 46 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/5#-NgwjVTQ-fmhOlsHHuno:-Nh1PCMy0_IGtNxaR4KE:b-te1otv) ([raw file](https://github.com/saltastroops/nir-simulator/blob/ae7efabe2e8dd6b49cc9a0e66ed1b11b9a3c2ac3/backend/backend/modules/data/throughput.py#L46)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Can we discuss the way the data is handled?
</blockquote></details>

Postponed To another PR
___
*[`backend/backend/views/throughput.py` line 18 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/5#-NgwfeKb2DUNaERZqkkr:-Nh0t5Ns53HeK6siAuzv:b2sgk0c) ([raw file](https://github.com/saltastroops/nir-simulator/blob/ae7efabe2e8dd6b49cc9a0e66ed1b11b9a3c2ac3/backend/backend/views/throughput.py#L18)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

In the absence of a proper REST framework used, maybe you should just assume a POST request. (In particular because the code doesn't seem to handle non-POST requests properly. (They may not fail, but they may also not do what the user expects, as their configuration details won't be used.)
</blockquote></details>

if  is removed
___
*[`backend/backend/views/throughput.py` line 22 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/5#-NgwfQvM9uXP3rZkygbU:-Nh0t9XD6QJGFm5BMdzl:b-pgjemm) ([raw file](https://github.com/saltastroops/nir-simulator/blob/ae7efabe2e8dd6b49cc9a0e66ed1b11b9a3c2ac3/backend/backend/views/throughput.py#L22)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

From here on, the "default_options" are no default options any longer...
</blockquote></details>

calling it form data
___
*[`react/src/App.jsx` line 5 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/5#-Ngwgpzz99wGsy_-S0qG:-Nh0tRXHAagnhqhYe5yt:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/ae7efabe2e8dd6b49cc9a0e66ed1b11b9a3c2ac3/react/src/App.jsx#L5)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

// Register the controllers and elements for the charts
</blockquote></details>

Done.
___
*[`react/src/components/configure/TelescopeConfigure.css` line 2 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/5#-NgwjJBQ4coU4zxqMtCb:-Nh0teZHE9rrdc-f3YZA:bujyvwq) ([raw file](https://github.com/saltastroops/nir-simulator/blob/ae7efabe2e8dd6b49cc9a0e66ed1b11b9a3c2ac3/react/src/components/configure/TelescopeConfigure.css#L2)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Can we discuss this?
</blockquote></details>

Will address in the future PR
___
*[`react/src/components/configure/TelescopeConfigure.jsx` line 1 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/5#-NgwhnrA3DXkUdZRSV4W:-Nh1PJ4oEdosM8kAuZwM:b-kt8jy8) ([raw file](https://github.com/saltastroops/nir-simulator/blob/ae7efabe2e8dd6b49cc9a0e66ed1b11b9a3c2ac3/react/src/components/configure/TelescopeConfigure.jsx#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Should be reviewed and modified after PR #7 has been merged.
</blockquote></details>

Yes, please
___
*[`react/src/components/configure/TelescopeConfigure.jsx` line 64 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/5#-NgwhUuWE3mMHFEq6b_k:-Nh14QBb3jJ0HaJqrOuu:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/ae7efabe2e8dd6b49cc9a0e66ed1b11b9a3c2ac3/react/src/components/configure/TelescopeConfigure.jsx#L64)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The URL should not be hardcoded.
</blockquote></details>

Done.
___
*[`react/src/components/configure/TelescopeConfigure.jsx` line 83 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/5#-NgwlleW-9ORjtnb_Z_T:-Nh151AZ8_qKyVYfeyP7:b-84847m) ([raw file](https://github.com/saltastroops/nir-simulator/blob/ae7efabe2e8dd6b49cc9a0e66ed1b11b9a3c2ac3/react/src/components/configure/TelescopeConfigure.jsx#L83)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't this be defined in the plot class?
</blockquote></details>

Moved
___
*[`react/src/components/configure/TelescopeConfigure.jsx` line 104 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/5#-NgwlSTI9HAyywcBrlcw:-Nh1ND2Q1moYon1ApJ6Y:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/ae7efabe2e8dd6b49cc9a0e66ed1b11b9a3c2ac3/react/src/components/configure/TelescopeConfigure.jsx#L104)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This is a long piece of code, and splitting it up into different pieces might make it more readable.
</blockquote></details>

Done.
___
*[`react/src/components/exposure/MakeAnExposure.jsx` line 1 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/5#-Ngwi1_sCIwQ8ijJL8uj:-Nh1NFCN3m76KovyI1C2:bmmvacg) ([raw file](https://github.com/saltastroops/nir-simulator/blob/ae7efabe2e8dd6b49cc9a0e66ed1b11b9a3c2ac3/react/src/components/exposure/MakeAnExposure.jsx#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Should be reviewed ands modified after PR #7 has been merged.
</blockquote></details>

yes, please
___
*[`react/src/components/general-spectra/GeneralSpectra.jsx` line 2 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/5#-Ngwi4po4thXEvyGDYN4:-Nh1NKAG5NlD-q-nIvw1:bmmvacg) ([raw file](https://github.com/saltastroops/nir-simulator/blob/ae7efabe2e8dd6b49cc9a0e66ed1b11b9a3c2ac3/react/src/components/general-spectra/GeneralSpectra.jsx#L2)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Should be reviewed ands modified after PR #7 has been merged.
</blockquote></details>

yes, please
___
*[`react/src/components/plots/LinePlot.jsx` line 1 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/5#-Ngwkbyo6-8IVXjCRPfU:-Nh1Os2hCNDjrT3jCSDz:b-yt5zi9) ([raw file](https://github.com/saltastroops/nir-simulator/blob/ae7efabe2e8dd6b49cc9a0e66ed1b11b9a3c2ac3/react/src/components/plots/LinePlot.jsx#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The name "LinePlot" is misleading, as this is a throughput plot, not a general line plot.
</blockquote></details>

fixed to be general
___
*[`react/src/components/plots/LinePlot.jsx` line 16 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/5#-Ngwjei48bkY2SQ6nOnS:-Nh1OwKcDvSN0fN4JfLu:b-q8y63y) ([raw file](https://github.com/saltastroops/nir-simulator/blob/ae7efabe2e8dd6b49cc9a0e66ed1b11b9a3c2ac3/react/src/components/plots/LinePlot.jsx#L16)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Isn't the comment a bit redundant? :-)
</blockquote></details>

yes it was
___
*[`react/src/components/plots/LinePlot.jsx` line 29 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/5#-NgwkAzD5lsXiVOZ4v2F:-Nh1OyG_92lCItFcjdAQ:b-hfpv0l) ([raw file](https://github.com/saltastroops/nir-simulator/blob/ae7efabe2e8dd6b49cc9a0e66ed1b11b9a3c2ac3/react/src/components/plots/LinePlot.jsx#L29)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why do you enable panning?
</blockquote></details>

removed
___
*[`react/src/components/plots/linePlot.css` line 1 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/5#-NgwiH7K1NdZRhVrKhgc:-Nh1OzlN3Cut-dd48Zly:b-e1w3ys) ([raw file](https://github.com/saltastroops/nir-simulator/blob/ae7efabe2e8dd6b49cc9a0e66ed1b11b9a3c2ac3/react/src/components/plots/linePlot.css#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Can we discuss this, please?
</blockquote></details>

Will fix on another PR

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/nir-simulator/5)* status: all files reviewed, 5 unresolved discussions (waiting on @hettlage)

___
*[`backend/backend/settings.py` line 157 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/5#-Nh1i89E0xAx4TLDpT-y:-Nh1tqU991oKmrL9GFVL:b-kxjq2m) ([raw file](https://github.com/saltastroops/nir-simulator/blob/2f6c0e4f922dc2995e2e7b22968cd4a55966276c/backend/backend/settings.py#L157)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Probably unnecessary?
</blockquote></details>

Ahh yes forgot to remove not used anyway
___
*[`react/src/components/Tabs.jsx` line 56 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/5#-Nh1jGNg6GMUB6pcl34d:-Nh1uNv76qei5h7TKT24:b-hfpv0l) ([raw file](https://github.com/saltastroops/nir-simulator/blob/2f6c0e4f922dc2995e2e7b22968cd4a55966276c/react/src/components/Tabs.jsx#L56)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think you need to use the display style any longer, given that reducing the number of data points solves the issue?
</blockquote></details>

removed
___
*[`react/src/components/configure/TelescopeConfigure.jsx` line 49 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/5#-Nh1kZ-FBXuMNpxXrxTG:-Nh1vwkJ2fUVD8wk1O58:bn9adhr) ([raw file](https://github.com/saltastroops/nir-simulator/blob/2f6c0e4f922dc2995e2e7b22968cd4a55966276c/react/src/components/configure/TelescopeConfigure.jsx#L49)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think this is correct; form data should one passed as its to the body.
</blockquote></details>

slipped through
___
*[`react/src/components/plots/LinePlot.jsx` line 1 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/5#-Ngwkbyo6-8IVXjCRPfU:-Nh1wPfU594IjP75nQY4:b2cbgqr) ([raw file](https://github.com/saltastroops/nir-simulator/blob/ae7efabe2e8dd6b49cc9a0e66ed1b11b9a3c2ac3/react/src/components/plots/LinePlot.jsx#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'm tempted to suggest a different approach. Can we discuss this?
</blockquote></details>

we can discuss
___
*[`react/src/environmets/environment.prod.ts` line 2 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/5#-Nh1mBHbCHbBO2sMO8aR:-Nh1w7Wa0tLglYWIfIax:b-b736ac) ([raw file](https://github.com/saltastroops/nir-simulator/blob/2f6c0e4f922dc2995e2e7b22968cd4a55966276c/react/src/environmets/environment.prod.ts#L2)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This is definitely not a production URL...
</blockquote></details>

100% correct but I can't build if this is nothing.. will address as soon as we have a production URL

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/nir-simulator/5)* status: all files reviewed, 3 unresolved discussions (waiting on @Eb-Zeero)

___
*[`react/src/components/plots/LinePlot.jsx` line 4 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/5#-Nh2H6f60inZzjFMdHXj:-Nh2H6f60inZzjFMdHXk:bvu0ngu) ([raw file](https://github.com/saltastroops/nir-simulator/blob/2f6c0e4f922dc2995e2e7b22968cd4a55966276c/react/src/components/plots/LinePlot.jsx#L4)):*
> ```JavaScript
> import { Line } from 'react-chartjs-2';
> 
> export function LinePlot({data, isOutdated}) {
> ```

Given that the <Line> component expects a `data` and an `options` property, it might be reasonable to make the distinction for `LinePlot` as well, passing `data` and `options` as separate properties.
___
*[`react/src/components/plots/PlotOptions.ts` line 1 at r4](https://reviewable.io/reviews/saltastroops/nir-simulator/5#-Nh2HaplDjVOcXioOmeK:-Nh2HaplDjVOcXioOmeL:b-t63g2y) ([raw file](https://github.com/saltastroops/nir-simulator/blob/194fd5081677cde1c3813e3fe6e619cb30b9c336/react/src/components/plots/PlotOptions.ts#L1)):*
> ```XML
> interface  Options {
> ```

Isn't that name a bit too generic?
___
*[`react/src/environmets/environment.prod.ts` line 2 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/5#-Nh1mBHbCHbBO2sMO8aR:-Nh2I1Nx5iHayPOmREls:b-pyamz1) ([raw file](https://github.com/saltastroops/nir-simulator/blob/2f6c0e4f922dc2995e2e7b22968cd4a55966276c/react/src/environmets/environment.prod.ts#L2)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

100% correct but I can't build if this is nothing.. will address as soon as we have a production URL
</blockquote></details>

But you could use a URL like example.com -- that way it will at least fail if you try it locally (as it should).

**Review by hettlage — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/nir-simulator/5)* status: all files reviewed, 3 unresolved discussions (waiting on @Eb-Zeero)

**Pull request merged**
