### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by hettlage**
The plot currently does not indicate that it is outdated. This will be addressed in a future commit.

- - -
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/nir-simulator/10)

### CODE REVIEW

**Review by Eb-Zeero — CHANGES_REQUESTED** [review]
> Reviewed 26 of 28 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/nir-simulator/10)* status: 26 of 28 files reviewed, 8 unresolved discussions (waiting on @hettlage)

___
*[`react/src/components/instrument/ImagingConfigurationPanel.tsx` line 1 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/10#-Nh5qsoe27mN-pnuYLk2:-Nh5qsoe27mN-pnuYLk3:bdbbkbt) ([raw file](https://github.com/saltastroops/nir-simulator/blob/515b36fbb2d5f358b3effb108164f0db397a9e80/react/src/components/instrument/ImagingConfigurationPanel.tsx#L1)):*
> ```XML
> import { InstrumentMode } from "../../types.ts";
> ```

I do not think this file should be a .tsx .tx will do just fine
___
*[`react/src/components/instrument/ImagingConfigurationPanel.tsx` line 12 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/10#-Nh5i9F_Bn6K5bxEJTpL:-Nh5i9F_Bn6K5bxEJTpM:bobfyut) ([raw file](https://github.com/saltastroops/nir-simulator/blob/515b36fbb2d5f358b3effb108164f0db397a9e80/react/src/components/instrument/ImagingConfigurationPanel.tsx#L12)):*
> ```XML
> 
> export default function InstrumentConfigurationPanel() {
>   return <div></div>;
> ```

what is this panel for?
___
*[`react/src/components/instrument/InstrumentConfigurationPanel.tsx` line 78 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/10#-Nh5rP0zB2_QMFsHHXw9:-Nh5rP0zB2_QMFsHHXwA:b-s8nawh) ([raw file](https://github.com/saltastroops/nir-simulator/blob/515b36fbb2d5f358b3effb108164f0db397a9e80/react/src/components/instrument/InstrumentConfigurationPanel.tsx#L78)):*
> ```XML
>           new InstrumentConfiguration({
>             modeConfiguration: new ImagingConfiguration(),
>             filter: "Clear Filter",
> ```

You do not need to set the filter back to clear if LWBF
___
*[`react/src/components/instrument/InstrumentConfigurationPanel.tsx` line 86 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/10#-Nh5rl7dA3W3cJo_cdid:-Nh5rl7dA3W3cJo_cdie:b-s8nawh) ([raw file](https://github.com/saltastroops/nir-simulator/blob/515b36fbb2d5f358b3effb108164f0db397a9e80/react/src/components/instrument/InstrumentConfigurationPanel.tsx#L86)):*
> ```XML
>           new InstrumentConfiguration({
>             modeConfiguration: new SpectroscopyConfiguration(),
>             filter: "Clear Filter",
> ```

You do not need to set the filter back to clear if LWBF
___
*[`react/src/components/instrument/InstrumentConfigurationPanel.tsx` line 116 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/10#-Nh5q5gm2RNzgvWc8Bi7:-Nh5q5gm2RNzgvWc8Bi8:b-t2nale) ([raw file](https://github.com/saltastroops/nir-simulator/blob/515b36fbb2d5f358b3effb108164f0db397a9e80/react/src/components/instrument/InstrumentConfigurationPanel.tsx#L116)):*
> ```XML
>     const formData = new FormData();
>     Object.keys(data).forEach((key) =>
>       formData.append(key, data[key as keyof typeof data].toString()),
> ```

formData is never updated
___
*[`react/src/components/instrument/InstrumentConfigurationPanel.tsx` line 133 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/10#-Nh5tM_h0LFUTHyDRQhW:-Nh5tM_h0LFUTHyDRQhX:bna9t30) ([raw file](https://github.com/saltastroops/nir-simulator/blob/515b36fbb2d5f358b3effb108164f0db397a9e80/react/src/components/instrument/InstrumentConfigurationPanel.tsx#L133)):*
> ```XML
>       })
>       .then((data) => {
>         console.log({ data });
> ```

remove log statement
___
*[`react/src/components/instrument/InstrumentConfigurationPanel.tsx` line 206 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/10#-Nh5utuuEyFLUzGN4Yih:-Nh5utuuEyFLUzGN4Yii:b-lu3wyq) ([raw file](https://github.com/saltastroops/nir-simulator/blob/515b36fbb2d5f358b3effb108164f0db397a9e80/react/src/components/instrument/InstrumentConfigurationPanel.tsx#L206)):*
> ```XML
>               </div>
>             </div>
> ```

it would help if you had some margin or padding between these two components(Filter and Spectroscopy)
___
*[`react/src/components/plots/LinePlot.tsx` line 11 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/10#-Nh5tPfY7mxjYd4cxgoI:-Nh5tPfY7mxjYd4cxgoJ:bna9t30) ([raw file](https://github.com/saltastroops/nir-simulator/blob/515b36fbb2d5f358b3effb108164f0db397a9e80/react/src/components/plots/LinePlot.tsx#L11)):*
> ```XML
> 
> export function LinePlot({ chartContent, isOutdated }: Props) {
>   console.log({ chartContent });
> ```

remove log statement

**Review by hettlage — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/nir-simulator/10)* status: 22 of 30 files reviewed, 8 unresolved discussions (waiting on @Eb-Zeero)

___
*[`react/src/components/instrument/InstrumentConfigurationPanel.tsx` line 78 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/10#-Nh5rP0zB2_QMFsHHXw9:-Nh61SqT2Rgx-kKug3_A:b8go2vd) ([raw file](https://github.com/saltastroops/nir-simulator/blob/515b36fbb2d5f358b3effb108164f0db397a9e80/react/src/components/instrument/InstrumentConfigurationPanel.tsx#L78)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

You do not need to set the filter back to clear if LWBF
</blockquote></details>

Good catch. Thanks!
___
*[`react/src/components/instrument/InstrumentConfigurationPanel.tsx` line 86 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/10#-Nh5rl7dA3W3cJo_cdid:-Nh61WoPEslp968lrumB:b8go2vd) ([raw file](https://github.com/saltastroops/nir-simulator/blob/515b36fbb2d5f358b3effb108164f0db397a9e80/react/src/components/instrument/InstrumentConfigurationPanel.tsx#L86)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

You do not need to set the filter back to clear if LWBF
</blockquote></details>

Good catch. Thanks!
___
*[`react/src/components/instrument/InstrumentConfigurationPanel.tsx` line 133 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/10#-Nh5tM_h0LFUTHyDRQhW:-Nh622ThBaZJgN0Uu5gT:b9fwagl) ([raw file](https://github.com/saltastroops/nir-simulator/blob/515b36fbb2d5f358b3effb108164f0db397a9e80/react/src/components/instrument/InstrumentConfigurationPanel.tsx#L133)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

remove log statement
</blockquote></details>

Seems to be gone now.

**Review by Eb-Zeero — COMMENTED** [review]
> Reviewed 4 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/nir-simulator/10)* status: 26 of 30 files reviewed, 4 unresolved discussions (waiting on @hettlage)

**Review by hettlage — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/nir-simulator/10)* status: 15 of 32 files reviewed, 4 unresolved discussions (waiting on @Eb-Zeero)

___
*[`react/src/components/instrument/ImagingConfigurationPanel.tsx` line 1 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/10#-Nh5qsoe27mN-pnuYLk2:-Nh7xWkl9G6hdaeoYIw-:b2q5bqi) ([raw file](https://github.com/saltastroops/nir-simulator/blob/515b36fbb2d5f358b3effb108164f0db397a9e80/react/src/components/instrument/ImagingConfigurationPanel.tsx#L1)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

I do not think this file should be a .tsx .tx will do just fine
</blockquote></details>

See next comment.
___
*[`react/src/components/instrument/ImagingConfigurationPanel.tsx` line 12 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/10#-Nh5i9F_Bn6K5bxEJTpL:-Nh7xlPl-wRMIaEnWa8l:b-1kupxw) ([raw file](https://github.com/saltastroops/nir-simulator/blob/515b36fbb2d5f358b3effb108164f0db397a9e80/react/src/components/instrument/ImagingConfigurationPanel.tsx#L12)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

what is this panel for?
</blockquote></details>

I think that having an ImagingConfigurationPanel makes sense for consistency reasons.
___
*[`react/src/components/instrument/InstrumentConfigurationPanel.tsx` line 116 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/10#-Nh5q5gm2RNzgvWc8Bi7:-Nh8lWsn-RYHc3tHc7ay:b-rzmofc) ([raw file](https://github.com/saltastroops/nir-simulator/blob/515b36fbb2d5f358b3effb108164f0db397a9e80/react/src/components/instrument/InstrumentConfigurationPanel.tsx#L116)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

formData is never updated
</blockquote></details>

The problem was method binding. Should be fixed now.
___
*[`react/src/components/instrument/InstrumentConfigurationPanel.tsx` line 206 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/10#-Nh5utuuEyFLUzGN4Yih:-Nh8le0HC7pY-jWq6t2m:b-n5ci7g) ([raw file](https://github.com/saltastroops/nir-simulator/blob/515b36fbb2d5f358b3effb108164f0db397a9e80/react/src/components/instrument/InstrumentConfigurationPanel.tsx#L206)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

it would help if you had some margin or padding between these two components(Filter and Spectroscopy)
</blockquote></details>

Will be addressed in a future PR, if possible.
___
*[`react/src/components/plots/LinePlot.tsx` line 11 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/10#-Nh5tPfY7mxjYd4cxgoI:-Nh8lm63EkuWF1zaDI8d:b-flfbrq) ([raw file](https://github.com/saltastroops/nir-simulator/blob/515b36fbb2d5f358b3effb108164f0db397a9e80/react/src/components/plots/LinePlot.tsx#L11)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

remove log statement
</blockquote></details>

 Gone. :-)

**Review by Eb-Zeero — APPROVED** [review]
> Reviewed 1 of 6 files at r2, 16 of 16 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/nir-simulator/10)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hettlage)

**Pull request merged**
