### PR TITLE
Extrapolate observation for non-overlapping bandpass and source spectrum

### PR DESCRIPTION
**Pull request by mofokeng-chaka**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/nir-simulator/81)

### CODE REVIEW

**Review by Eb-Zeero — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/nir-simulator/81)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mofokeng-chaka)

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/nir-simulator/81)* status: all files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

___
*[`backend/nirwals/physics/exposure.py` line 99 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/81#-NoNqxMi6lqi9lUqPySD:-NoNqxMi6lqi9lUqPySE:b-s81ruj) ([raw file](https://github.com/saltastroops/nir-simulator/blob/d2efe86b62795cf2ea75ffb88e5fb46cae332ab6/backend/nirwals/physics/exposure.py#L99)):*
> ```Python
>             grating_constant=grating.grating_constant,
>         ),
>         force="extrap"
> ```

I'm hesitant about this change. Extrapolation might very well not be what you want, depending on the function which is extrapolated.

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/nir-simulator/81)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero and @hettlage)

___
*[`backend/nirwals/physics/exposure.py` line 99 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/81#-NoNqxMi6lqi9lUqPySD:-NtFLLWp5xvVeUlm8d8x:b-n46fq1) ([raw file](https://github.com/saltastroops/nir-simulator/blob/d2efe86b62795cf2ea75ffb88e5fb46cae332ab6/backend/nirwals/physics/exposure.py#L99)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'm hesitant about this change. Extrapolation might very well not be what you want, depending on the function which is extrapolated.
</blockquote></details>

You're right extrapolation is not what we want as the true source spectrum might end up being modified which may give incorrect results. Based on our previous discussions, the idea was to extend the source spectrum by adding zero-flux values to the edges. 

It turns out using `force="taper"` does exactly that. See https://synphot.readthedocs.io/en/latest/_modules/synphot/spectrum.html#BaseSpectrum.taper

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/nir-simulator/81)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero and @mofokeng-chaka)

___
*[`backend/nirwals/physics/exposure.py` line 99 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/81#-NoNqxMi6lqi9lUqPySD:-O-f-Vam3CpDrqa7E_Tp:bjj51ya) ([raw file](https://github.com/saltastroops/nir-simulator/blob/d2efe86b62795cf2ea75ffb88e5fb46cae332ab6/backend/nirwals/physics/exposure.py#L99)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

You're right extrapolation is not what we want as the true source spectrum might end up being modified which may give incorrect results. Based on our previous discussions, the idea was to extend the source spectrum by adding zero-flux values to the edges. 

It turns out using `force="taper"` does exactly that. See https://synphot.readthedocs.io/en/latest/_modules/synphot/spectrum.html#BaseSpectrum.taper
</blockquote></details>

What worries me, though, is that the function may taper off quite slowly, as the tapering depends on the ratio of the first and second (or last and last-but-one) wavelength.

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/nir-simulator/81)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero and @hettlage)

___
*[`backend/nirwals/physics/exposure.py` line 99 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/81#-NoNqxMi6lqi9lUqPySD:-O08hWOa9-frnK6Ia9tz:bq7lxd7) ([raw file](https://github.com/saltastroops/nir-simulator/blob/d2efe86b62795cf2ea75ffb88e5fb46cae332ab6/backend/nirwals/physics/exposure.py#L99)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

What worries me, though, is that the function may taper off quite slowly, as the tapering depends on the ratio of the first and second (or last and last-but-one) wavelength.
</blockquote></details>

As per our discussion, you suggested that this functionality is probably implemented already. I reviewed the code and couldn't find it anywhere, the only method that performs a similar process is the `shift` method in `physics/utils.py` file. The `shift` method might be useful, however it raises another issue, the wavelength value to use for assigning a zero-flux value(s), as some values might cause

**Review by mofokeng-chaka — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/nir-simulator/81#-:-OBiTn7K6hi3CHzSUflp:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @hettlage)

**Pull request merged**
