### PR TITLE
Setting plots to outdated

### PR DESCRIPTION
**Pull request by Eb-Zeero**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/nir-simulator/77)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/nir-simulator/77)* status: all files reviewed, 17 unresolved discussions (waiting on @Eb-Zeero)

___
*[`frontend/tailwind.config.js` line 7 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/77#-NoLX1RW9Zl-TFKTWKJ0:-NoLX1RW9Zl-TFKTWKJ1:b7l2lcf) ([raw file](https://github.com/saltastroops/nir-simulator/blob/f97aff11d74726eb9568ae618f2ba41d3a400a7d/frontend/tailwind.config.js#L7)):*
> ```JavaScript
>   theme: {
>     extend: {},
>     screens: {
> ```

This configuration should be unnecessary.
___
*[`frontend/src/components/plots/linePlot.css` line 11 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/77#-NoLoKLj89TxuUOKkz18:-NoLoKLj89TxuUOKkz19:bpgt2lt) ([raw file](https://github.com/saltastroops/nir-simulator/blob/de542139cab6e755b27c2073f7301a480a772364/frontend/src/components/plots/linePlot.css#L11)):*
> ```CSS
>     position: absolute;
>     top: 100px;
>     left: 55%;
> ```

This probably should be 50%.  (Look at the alignment with the plot title.)
___
*[`frontend/src/components/plots/linePlot.css` line 15 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/77#-NoLovxc9oTs_v7AsW_G:-NoLovxc9oTs_v7AsW_H:brg97ml) ([raw file](https://github.com/saltastroops/nir-simulator/blob/de542139cab6e755b27c2073f7301a480a772364/frontend/src/components/plots/linePlot.css#L15)):*
> ```CSS
>     font-size: 6vw;
>     color: rgba(255, 0, 0, 0.5); /* Set the opacity for transparency */
>     pointer-events: none;
> ```

The `pointer-events` style should be unnecessary?
___
*[`frontend/src/components/spectrum/SpectrumGenerationTab.tsx` line 104 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/77#-NoLP5Bz6ei86cuQ1OWY:-NoLP5Bz6ei86cuQ1OWZ:b-uoojuo) ([raw file](https://github.com/saltastroops/nir-simulator/blob/f97aff11d74726eb9568ae618f2ba41d3a400a7d/frontend/src/components/spectrum/SpectrumGenerationTab.tsx#L104)):*
> ```XML
>   const [plotMetadata, setPlotMetadata] = useState({} as any);
> 
>   const currentMetadata = exposureFormData(setup);
> ```

This should be `spectrumFormData`.
___
*[`frontend/src/components/spectrum/SpectrumGenerationTab.tsx` line 108 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/77#-NoL_EmO3lKOoP0ksR-K:-NoL_EmPCeWzqqQBRMes:b-sg8q5h) ([raw file](https://github.com/saltastroops/nir-simulator/blob/f97aff11d74726eb9568ae618f2ba41d3a400a7d/frontend/src/components/spectrum/SpectrumGenerationTab.tsx#L108)):*
> ```XML
> 
>   return (
>     <div className="flex flex-col md:flex-row">
> ```

You should center the components on a small screen; so you should add styling like `items-center md:items-start`.
___
*[`frontend/src/components/spectrum/SpectrumGenerationTab.tsx` line 170 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/77#-NoL_xhv3QNpY2z9n0jL:-NoL_xhv3QNpY2z9n0jM:bfl0bem) ([raw file](https://github.com/saltastroops/nir-simulator/blob/f97aff11d74726eb9568ae618f2ba41d3a400a7d/frontend/src/components/spectrum/SpectrumGenerationTab.tsx#L170)):*
> ```XML
>         {!sourceChartContent.requested && (
>           <div className={"relative md:h-screen"}>
>             <p className={"absolute top-10 left-10 m-4"}>
> ```

Why should this be positioned absolutely?

Also, you might consider hiding this on a small screen.
___
*[`frontend/src/components/spectrum/SpectrumGenerationTab.tsx` line 171 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/77#-NoLWG-QCC_Bx_pje2db:-NoLWG-QCC_Bx_pje2dc:be2yffd) ([raw file](https://github.com/saltastroops/nir-simulator/blob/f97aff11d74726eb9568ae618f2ba41d3a400a7d/frontend/src/components/spectrum/SpectrumGenerationTab.tsx#L171)):*
> ```XML
>           <div className={"relative md:h-screen"}>
>             <p className={"absolute top-10 left-10 m-4"}>
>               Press the "Show Spectrum" to generate the plots
> ```

to generate > button to generate
___
*[`frontend/src/components/spectrum/SpectrumGenerationTab.tsx` line 169 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/77#-NoLm8Wt7esdzUJdJdxz:-NoLm8Wt7esdzUJdJdy-:b95xhqa) ([raw file](https://github.com/saltastroops/nir-simulator/blob/de542139cab6e755b27c2073f7301a480a772364/frontend/src/components/spectrum/SpectrumGenerationTab.tsx#L169)):*
> ```XML
>       <div className="ml-2 w-full">
>         {!sourceChartContent.requested && (
>           <div className={"relative md:h-screen"}>
> ```

Does the `h-screen` have any effect?
___
*[`frontend/src/components/exposure/ExposureTab.tsx` line 167 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/77#-NoLnA44-g6Wce6rWhf8:-NoLnA44-g6Wce6rWhf9:b-u9yenw) ([raw file](https://github.com/saltastroops/nir-simulator/blob/de542139cab6e755b27c2073f7301a480a772364/frontend/src/components/exposure/ExposureTab.tsx#L167)):*
> ```XML
>     [chartContent],
>   );
>   console.log(setup);
> ```

Unnecessary log statement
___
*[`frontend/src/components/exposure/ExposureTab.tsx` line 226 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/77#-NoLmynF2y04E_7ouP1m:-NoLmynF2y04E_7ouP1n:b-sg8q5h) ([raw file](https://github.com/saltastroops/nir-simulator/blob/de542139cab6e755b27c2073f7301a480a772364/frontend/src/components/exposure/ExposureTab.tsx#L226)):*
> ```XML
>   return (
>     <div>
>       <div className="flex flex-col md:flex-row">
> ```

You should center the components on a small screen; so you should add styling like `items-center md:items-start`.
___
*[`frontend/src/components/exposure/ExposureTab.tsx` line 260 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/77#-NoLmwdq9lxjauttL6qb:-NoLmwdq9lxjauttL6qc:b95xhqa) ([raw file](https://github.com/saltastroops/nir-simulator/blob/de542139cab6e755b27c2073f7301a480a772364/frontend/src/components/exposure/ExposureTab.tsx#L260)):*
> ```XML
>         <div className="ml-2 w-full">
>           {!chartContent.requested && (
>             <div className={"relative md:h-screen"}>
> ```

Does the `h-screen` have any effect?
___
*[`frontend/src/components/exposure/ExposureTab.tsx` line 262 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/77#-NoLn0xo4J49-DaPILRJ:-NoLn0xp6X_2SGDF-Vey:bfl0bem) ([raw file](https://github.com/saltastroops/nir-simulator/blob/de542139cab6e755b27c2073f7301a480a772364/frontend/src/components/exposure/ExposureTab.tsx#L262)):*
> ```XML
>             <div className={"relative md:h-screen"}>
>               {setup.exposureConfiguration.activeQuery === "SNR" && (
>                 <p className={"absolute top-10 left-10 m-4"}>
> ```

Why should this be positioned absolutely?

Also, you might consider hiding this on a small screen.
___
*[`frontend/src/components/exposure/ExposureTab.tsx` line 268 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/77#-NoLn3L0-6ixsvHFstgt:-NoLn3L13DO_JPzX2H2R:be2yffd) ([raw file](https://github.com/saltastroops/nir-simulator/blob/de542139cab6e755b27c2073f7301a480a772364/frontend/src/components/exposure/ExposureTab.tsx#L268)):*
> ```XML
>               {setup.exposureConfiguration.activeQuery === "ExposureTime" && (
>                 <p className={"absolute top-10 left-10 m-4"}>
>                   Press the "Show Exposure Time" to generate the plots
> ```

to generate > button to generate
___
*[`frontend/src/components/instrument/InstrumentConfigurationTab.tsx` line 148 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/77#-NoLmeVYC1cygoSTIeiZ:-NoLmeVYC1cygoSTIei_:b-sg8q5h) ([raw file](https://github.com/saltastroops/nir-simulator/blob/de542139cab6e755b27c2073f7301a480a772364/frontend/src/components/instrument/InstrumentConfigurationTab.tsx#L148)):*
> ```XML
>   return (
>     <div>
>       <div className="flex flex-col md:flex-row">
> ```

You should center the components on a small screen; so you should add styling like `items-center md:items-start`.
___
*[`frontend/src/components/instrument/InstrumentConfigurationTab.tsx` line 249 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/77#-NoLmoMiAO8UKei-9t_I:-NoLmoMiAO8UKei-9t_J:b95xhqa) ([raw file](https://github.com/saltastroops/nir-simulator/blob/de542139cab6e755b27c2073f7301a480a772364/frontend/src/components/instrument/InstrumentConfigurationTab.tsx#L249)):*
> ```XML
>         <div className="ml-2 w-full">
>           {!chartContent.requested && (
>             <div className={"relative md:h-screen"}>
> ```

Does the `h-screen` have any effect?
___
*[`frontend/src/components/instrument/InstrumentConfigurationTab.tsx` line 250 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/77#-NoLmYo347pKboBGDvZd:-NoLmYo347pKboBGDvZe:bfl0bem) ([raw file](https://github.com/saltastroops/nir-simulator/blob/de542139cab6e755b27c2073f7301a480a772364/frontend/src/components/instrument/InstrumentConfigurationTab.tsx#L250)):*
> ```XML
>           {!chartContent.requested && (
>             <div className={"relative md:h-screen"}>
>               <p className={"absolute top-10 left-10 m-4"}>
> ```

Why should this be positioned absolutely?

Also, you might consider hiding this on a small screen.
___
*[`frontend/src/components/instrument/InstrumentConfigurationTab.tsx` line 251 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/77#-NoLmN4r6wcykru8KazZ:-NoLmN4r6wcykru8Kaz_:be2yffd) ([raw file](https://github.com/saltastroops/nir-simulator/blob/de542139cab6e755b27c2073f7301a480a772364/frontend/src/components/instrument/InstrumentConfigurationTab.tsx#L251)):*
> ```XML
>             <div className={"relative md:h-screen"}>
>               <p className={"absolute top-10 left-10 m-4"}>
>                 Press the "Show Throughput" to generate the plots
> ```

to generate > button to generate

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/nir-simulator/77)* status: all files reviewed, 17 unresolved discussions (waiting on @hettlage)

___
*[`frontend/tailwind.config.js` line 7 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/77#-NoLX1RW9Zl-TFKTWKJ0:-NoM2IPqBS59AR49ZIJB:brgawa8) ([raw file](https://github.com/saltastroops/nir-simulator/blob/f97aff11d74726eb9568ae618f2ba41d3a400a7d/frontend/tailwind.config.js#L7)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This configuration should be unnecessary.
</blockquote></details>

removed yes this sre defaults
___
*[`frontend/src/components/plots/linePlot.css` line 11 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/77#-NoLoKLj89TxuUOKkz18:-NoM2jW74u3HJaukDXMN:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/de542139cab6e755b27c2073f7301a480a772364/frontend/src/components/plots/linePlot.css#L11)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This probably should be 50%.  (Look at the alignment with the plot title.)
</blockquote></details>

Done.
___
*[`frontend/src/components/plots/linePlot.css` line 15 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/77#-NoLovxc9oTs_v7AsW_G:-NoM16hj6pSG3l6PwvOS:br989f9) ([raw file](https://github.com/saltastroops/nir-simulator/blob/de542139cab6e755b27c2073f7301a480a772364/frontend/src/components/plots/linePlot.css#L15)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The `pointer-events` style should be unnecessary?
</blockquote></details>

without this, you can place a cursor between text if you click on text. I found it weird as it is a big text
___
*[`frontend/src/components/spectrum/SpectrumGenerationTab.tsx` line 104 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/77#-NoLP5Bz6ei86cuQ1OWY:-NoM1kp4AwwAmqNPa6tR:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/f97aff11d74726eb9568ae618f2ba41d3a400a7d/frontend/src/components/spectrum/SpectrumGenerationTab.tsx#L104)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This should be `spectrumFormData`.
</blockquote></details>

Done.
___
*[`frontend/src/components/spectrum/SpectrumGenerationTab.tsx` line 108 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/77#-NoL_EmO3lKOoP0ksR-K:-NoM9l-80a_7hB4WO04W:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/f97aff11d74726eb9568ae618f2ba41d3a400a7d/frontend/src/components/spectrum/SpectrumGenerationTab.tsx#L108)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You should center the components on a small screen; so you should add styling like `items-center md:items-start`.
</blockquote></details>

Done.
___
*[`frontend/src/components/spectrum/SpectrumGenerationTab.tsx` line 170 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/77#-NoL_xhv3QNpY2z9n0jL:-NoMBHYR09O0176L2LnH:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/f97aff11d74726eb9568ae618f2ba41d3a400a7d/frontend/src/components/spectrum/SpectrumGenerationTab.tsx#L170)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why should this be positioned absolutely?

Also, you might consider hiding this on a small screen.
</blockquote></details>

Done.
___
*[`frontend/src/components/spectrum/SpectrumGenerationTab.tsx` line 171 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/77#-NoLWG-QCC_Bx_pje2db:-NoM2FCk5j7LHMTzCc9C:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/f97aff11d74726eb9568ae618f2ba41d3a400a7d/frontend/src/components/spectrum/SpectrumGenerationTab.tsx#L171)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

to generate > button to generate
</blockquote></details>

Done.
___
*[`frontend/src/components/spectrum/SpectrumGenerationTab.tsx` line 169 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/77#-NoLm8Wt7esdzUJdJdxz:-NoM26Yp6MVyaXdixiaH:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/de542139cab6e755b27c2073f7301a480a772364/frontend/src/components/spectrum/SpectrumGenerationTab.tsx#L169)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Does the `h-screen` have any effect?
</blockquote></details>

Done.
___
*[`frontend/src/components/exposure/ExposureTab.tsx` line 167 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/77#-NoLnA44-g6Wce6rWhf8:-NoLzmw9CjHXehoE-hW-:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/de542139cab6e755b27c2073f7301a480a772364/frontend/src/components/exposure/ExposureTab.tsx#L167)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Unnecessary log statement
</blockquote></details>

Done.
___
*[`frontend/src/components/exposure/ExposureTab.tsx` line 226 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/77#-NoLmynF2y04E_7ouP1m:-NoM9fOS8OoK2VxCU-mG:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/de542139cab6e755b27c2073f7301a480a772364/frontend/src/components/exposure/ExposureTab.tsx#L226)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You should center the components on a small screen; so you should add styling like `items-center md:items-start`.
</blockquote></details>

Done.
___
*[`frontend/src/components/exposure/ExposureTab.tsx` line 260 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/77#-NoLmwdq9lxjauttL6qb:-NoM0cgC6tHcE7MHOxxX:b-hfpv0l) ([raw file](https://github.com/saltastroops/nir-simulator/blob/de542139cab6e755b27c2073f7301a480a772364/frontend/src/components/exposure/ExposureTab.tsx#L260)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Does the `h-screen` have any effect?
</blockquote></details>

removed
___
*[`frontend/src/components/exposure/ExposureTab.tsx` line 262 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/77#-NoLn0xo4J49-DaPILRJ:-NoMBFkoEABZ0zxcmhFv:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/de542139cab6e755b27c2073f7301a480a772364/frontend/src/components/exposure/ExposureTab.tsx#L262)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why should this be positioned absolutely?

Also, you might consider hiding this on a small screen.
</blockquote></details>

Done.
___
*[`frontend/src/components/exposure/ExposureTab.tsx` line 268 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/77#-NoLn3L0-6ixsvHFstgt:-NoM0uRvBDLHI37oEblD:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/de542139cab6e755b27c2073f7301a480a772364/frontend/src/components/exposure/ExposureTab.tsx#L268)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

to generate > button to generate
</blockquote></details>

Done.
___
*[`frontend/src/components/instrument/InstrumentConfigurationTab.tsx` line 148 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/77#-NoLmeVYC1cygoSTIeiZ:-NoM-dQQCD2BmCCBmP4-:bhxslkk) ([raw file](https://github.com/saltastroops/nir-simulator/blob/de542139cab6e755b27c2073f7301a480a772364/frontend/src/components/instrument/InstrumentConfigurationTab.tsx#L148)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You should center the components on a small screen; so you should add styling like `items-center md:items-start`.
</blockquote></details>

I need to move the plots to the bottom of the screen if the screen gets to be too small
___
*[`frontend/src/components/instrument/InstrumentConfigurationTab.tsx` line 249 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/77#-NoLmoMiAO8UKei-9t_I:-NoM2ciK2tgd8Kq_GKel:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/de542139cab6e755b27c2073f7301a480a772364/frontend/src/components/instrument/InstrumentConfigurationTab.tsx#L249)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Does the `h-screen` have any effect?
</blockquote></details>

Done.
___
*[`frontend/src/components/instrument/InstrumentConfigurationTab.tsx` line 250 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/77#-NoLmYo347pKboBGDvZd:-NoMBGvE57ajaBMtrIbx:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/de542139cab6e755b27c2073f7301a480a772364/frontend/src/components/instrument/InstrumentConfigurationTab.tsx#L250)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why should this be positioned absolutely?

Also, you might consider hiding this on a small screen.
</blockquote></details>

Done.
___
*[`frontend/src/components/instrument/InstrumentConfigurationTab.tsx` line 251 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/77#-NoLmN4r6wcykru8KazZ:-NoM9qPM4gaj0NO7l3v-:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/de542139cab6e755b27c2073f7301a480a772364/frontend/src/components/instrument/InstrumentConfigurationTab.tsx#L251)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

to generate > button to generate
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/nir-simulator/77)* status: all files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero)

___
*[`frontend/src/components/plots/linePlot.css` line 15 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/77#-NoLovxc9oTs_v7AsW_G:-NoNqEhT8xkOxNiWl7oa:bja9chp) ([raw file](https://github.com/saltastroops/nir-simulator/blob/de542139cab6e755b27c2073f7301a480a772364/frontend/src/components/plots/linePlot.css#L15)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

without this, you can place a cursor between text if you click on text. I found it weird as it is a big text
</blockquote></details>

Hmm, good point. But I cannot fully reproduce this, or I misunderstood you. Can we chat about this?

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/nir-simulator/77)* status: all files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`frontend/src/components/plots/linePlot.css` line 15 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/77#-NoLovxc9oTs_v7AsW_G:-NoQUXNXC7WPQxy4w-O7:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/de542139cab6e755b27c2073f7301a480a772364/frontend/src/components/plots/linePlot.css#L15)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Hmm, good point. But I cannot fully reproduce this, or I misunderstood you. Can we chat about this?
</blockquote></details>

Done.

**Review by hettlage — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/nir-simulator/77)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Eb-Zeero)

**Pull request merged**
